### ISSUE TITLE
Does the number of pets being brought in the room cause a health risk? 

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/room-meeting-topics#1]
We have dogs, cats, squirrels, unicorns and much more undefined stuff wandering around in the room. Can we still ensure an healthy climate among our regulars or do we need moar rulez?

**Comment by jdd-software** [comment]
Have you been drinking now again?

**Comment by Aralun** [comment]
I'm guaranteed hypoallergenic anyway.

**Comment by Tiny-Giant** [comment]
Moar ruelz 4 all! There is not a problem in the world that cannot be solved with arbitrary rules.
