### ISSUE TITLE
Tailor auto-comments

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/room-meeting-topics#10]
Now and then situations pop-up where an auto-comment doesn't result in the predicted outcome but instead cause an opposite effect, for example mentioned [here](https://meta.stackoverflow.com/questions/352575/how-could-i-handle-rude-and-offensive-comments-kindly).

User [Pekka 웃](https://meta.stackoverflow.com/users/187606/pekka-%ec%9b%83) suggests in a comment:  
*...there is something to be said for customizing comments a bit so they don't look like a standard message you post everywhere. [...] I can see how to someone in a bad mood/feeling intimidated by the place/being under a lot of stress a comment like that could come across as condescending. One could try to point out something that's wrong with the specific post*

Is this something we can incorporate in our [stock auto-comments](https://github.com/SO-Close-Vote-Reviewers/auto-comments/tree/master/sites/stackoverflow.com), maybe with having *extension points* or is the *shrug it off, move on* attitude enough? Do you use a common tactic to tailor those already?

If this is too specific, we could broaden the topic and ask ourselves: Is a rude/abusive/criticizing comment reason to review the used (auto)-comment and improve over it?

**Comment by makyen** [comment]
If we do desire to have extension points, the [AutoReviewComments script](https://stackapps.com/questions/2116/autoreviewcomments-pro-forma-comments-for-se) has the ability to include a `[type here]` field in a comment, which is described as:

> If the text `[type here]` is included in a comment, it will be automatically selected for completion when inserted.

In addition, if you want to personalize the comment to the user, you can user either `[username]` or `[OP]`, both of which will be replaced with the OP's username.
