### ISSUE TITLE
Should people be allowed to post approve-pls requests for their own tag-wiki suggested edits which remove plagiarism?

### ISSUE THREAD

**Issue by makyen** [SO-Close-Vote-Reviewers/room-meeting-topics#12]
Should we permit people to post `approve-pls` requests about their own suggested edits when both of the following conditions apply:
1. It is a tag wiki edit (the tag's wiki entry or excerpt).
2. The edit is removing plagiarism, or is some other seriously important moderation-based change.

We've had a few requests matching these circumstances over the last several months.

Some additional context is available in the discussion for [pull request #8](https://github.com/SO-Close-Vote-Reviewers/socvr-website-content/pull/8).
Full disclosure: I've made [one such request](https://chat.stackoverflow.com/transcript/41570?m=36508412#36508412).

**Comment by NathanOliver1** [comment]
Personally I don't want these.  It basically gives you a privilege you have not earned yet.  I propose we change rule 15 from *Do not request action on a post that you have asked or answered.* to *Do not request action on a post/edit that you have a stake in.*.
