### ISSUE TITLE
Is there any possibility that if we rant enough we can lower the cv's needed to close a question?

### ISSUE THREAD

**Issue by jdd-software** [SO-Close-Vote-Reviewers/room-meeting-topics#14]
Do we all agree that the cv queue is broke?, if so should we push as a room to try and fix the problem?

The most obvious solution would be to rant to the DAG team that they need to lower the cv needed to close a question another can be to take turns and ping Shog9 every day.

Should we rant or who gives we close what we can and hope that dv does the rest?

**Comment by rschrieken** [comment]
I'm not sure if ranting is right thing to do. If you want this to happen you need stats that prove that lowering the number of votes required will indeed close significantly more questions. Keep in mind that the current ageing rules keep the CVQ under control. I'm not sure if with 3 votes you make a big enough dent to have it definitely drop in numbers. I'm sure shog9   will tweak the rules to make it level out again.
