### ISSUE TITLE
Should we request a Channel?

### ISSUE THREAD

**Issue by Aralun** [SO-Close-Vote-Reviewers/room-meeting-topics#16]
[SO Channels](https://stackoverflow.com/channels) ([MSO](https://meta.stackoverflow.com/questions/352065/introducing-channels-qa-for-engineering-teams)) are a kind of private space on SO.

Should we request one for SOCVR to put stuff like FAQ elements, userscripts, questions from regulars or outsiders (or lost ROs I guess), whatever?

**Comment by rschrieken** [comment]
Has there much been, except maybe those photo's, that you not wanted to be public? I mean, which of the content we create, either as RO or regulars, is not for consumption by the community at large or is so sensitive it should kept private.

**Comment by gunr2171** [comment]
Plus, having a person join a private channel just to get an answer or ask a question is a HUGE barrier to entry.

**Comment by Aralun** [comment]
I don't know if there's any option to make it semi-public (publicly readable at least?). If not, yep it's pretty meh.

**Comment by Aralun** [comment]
Never mind. This could probably be discussed later, when Channels evolve to provide semi-public features. For now it would be a waste of time. Deferring.

**Comment by rschrieken** [comment]
Channels  (now called Teams) is a paid option anyway, per user for that matter which I doubt any of us willing to provide the money for. Until SOCVR has its revenue stream sorted out this should be 
 indefinitely on hold. For that reason I close it now.
