### ISSUE TITLE
Assign someone the job to update the content of SOCVR.org

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/room-meeting-topics#2]
A lot of the non-FAQ content on our website is either out of date or not user friendly. This task is to spruce up the site to make it easier for readers to find what they are looking for, take out unimportant stuff, and clean up the rest.

Site styles can be modified as well. Communicate with gunr if more features need to be added to the server.

**Comment by Aralun** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-may-topic-6)

It's been decided that we should leverage GitHub issues and simply communicate about them in the room.
