### ISSUE TITLE
Can we revisit a rule or FAQ about prescribed close reasons?

### ISSUE THREAD

**Issue by Tyler-H** [SO-Close-Vote-Reviewers/room-meeting-topics#21]
I have often said (and seen others [ROs and non-ROs alike]) comment on some cv-pls requests, asking them to stick to the prescribed close reasons when posting cv-pls messages. The reasoning behind this is sound: the room should strive to be above reproach, and we don't need to put a target on our back by becoming a place where someone can post a cv-pls with the reason "trash question" or something similar. 

However, when I looked through the FAQ, I couldn't find anything about this, and I swear it used to be mentioned somewhere.

Can we get some clarification from the RO team on whether this is still in effect? If so, can it be added (back) to the FAQ, and a general reminder given to the room as a whole?

**Comment by makyen** [comment]
Using prescribed close reasons was discussed at the [January 2017 room meeting](https://socvr.org/room-info/room-meetings/2017-01), as an offshoot to the topic "[Do we need to watch our tone more?](http://chat.stackoverflow.com/rooms/108179/conversation/2017-january-topic-1)". The summary of the discussion was:

> Stick to the prescribed CV reasons when making requests, and always use constructive language when describing a question. We already require members to act professionally and with a high standard.

**Comment by Tyler-H** [comment]
@makyen In that case, I would like to adjust the question to:

Can we please discuss enforcement of prescribed close reasons? 

Currently we see lots of close reasons that use unnecessarily unfriendly language or terms in the close reasons by many users, several of which regularly use these inappropriate close reasons. 

However, I can count on one hand or less the number of times such a cv-pls request has been binned due to inappropriate close reasons or a failure to change it after prompting.

**Comment by makyen** [comment]
Given that we forgot to add it to the FAQ, it's a good idea to do so.

I agree that it should be enforced. My main concern is that I don't want to restrict it to *only* actual close reasons. I'd like to permit there to be additional factual information intended to help other users save time in evaluating the post. For example: "Typo: see 5th line of 2nd code block `foo` should be `bar`. Confirmed by OP in comments."

I definitely agree that derogatory language should not be used. If you see cases where such requests are not dealt with by an RO, please point them out, as we don't read every single thing, at least not immediately (varies based on how active each of us is in the room at that particular time).

It's also possible that  we've let things slide from time-to-time. Feel free to bring such to our attention.

**Comment by Tyler-H** [comment]
Certainly, custom close reasons should definitely remain available, but reasons like "zero value" "crap question" "no effort" etc. should not be permitted IMO. I see these used on an almost daily basis.
