### ISSUE TITLE
Revisit the use of the term "crap"

### ISSUE THREAD

**Issue by Tyler-H** [SO-Close-Vote-Reviewers/room-meeting-topics#22]
Per the new Code of Conduct (and to stop providing a potential crutch for users who might push the line a bit in requests), we should revisit instances of or references to the term "crap" in our FAQ. 

I believe in almost all cases we can replace "crap" with "low-quality posts" or "low-quality answers" without losing any meaning but gaining a lot of professional courtesy. I will follow up on this issue before the next meeting with a list of every instance (or if someone else beats me to it, that's fine).

**Comment by makyen** [comment]
The FAQ has been updated to remove the use of the word "crap".
