### ISSUE TITLE
Should 'bad' or 'wrong' *-pls requests be binnable with some 3rd party user consensus?

### ISSUE THREAD

**Issue by Tyler-H** [SO-Close-Vote-Reviewers/room-meeting-topics#24]
Regarding this conversation: https://chat.stackoverflow.com/rooms/41570/conversation/bin-wrong-cv-pls-requests

From time to time users may post a [cv-pls] (or other *-pls) request that is based on, or that contains, some factually or demonstrably wrong meta-data/reasoning. For example:

An inaccurate close reason may be used or the question may be described inaccurately:
 1. the 'general computing' close reason used for a question that is in fact about programming or a programming tool as defined by the Help Center
 3. no MCVE when in fact there is one
 3. no repro when it in fact may be reproducible
 4. and so on

There was no *clear* consensus when the room held an impromptu discussion on this. I was in favor of *some* kind of action the room community can take beyond:

   - waiting 3 days for the request to either fall past the threshold where the Room Cleanup script will bin it, **or more likely**, 

   - where enough people will see it, trust in the requestor's judgment (without seeing any ensuing counter comments), and vote on a question that ought not to be voted on a particular way.

There is also [precedent](https://chat.stackoverflow.com/transcript/41570?m=45366868#45366868) of Room Owners (hereafter referred to as 'RO') doing this. The suggestion then, is: 

**Whether at least two non-requesting\*, non-RO SOCVR members, providing clear and objective reasoning that a \*-pls request uses incorrect/inaccurate reasons--barring a logical/reasoned explanation for the choice by the requestor\**--qualifies said request for being manually binned by an RO (who should obviously agree with said consensus).**

It should be noted that, should such a policy be agreed upon and enacted, use of this action should not constitute a "punitive" action, nor be perceived, nor intended, as an action "against" a user, but rather as a corrective, educational action taken on a *request* to prevent unnecessary, incorrect, harmful, or undue action being taken on a question, comment, or answer that otherwise does not deserve said action.

\* - non-requesting here meaning two users *other* than the one who made the *-pls request. This means a total of **three** users (two normal and one RO) should agree explicitly (the two normal users by saying something, and the RO by binning) that the request is wrong/incorrect. If the requestor agrees that the request should be binned, they already have unilateral 'authority' to request for a Room Owner to do so, and should continue to do so under this proposed rule.

\*\* - if the requestor is able to provide a reasonable/logical explanation for their choice (e.g. *not* just "I skimmed the question and made this conclusion" or "I don't know enough about it to really say"), then the situation would be one of differing *informed* opinions, and thus should remain in the transcript. For lack of an immediate set of rules here, this would be left up to the participants of the discussion, with final ruling, as always, resting in the hands of the RO team, or moderators, if necessary.

**Comment by makyen** [comment]
The FAQ touches on situations along these lines: "[14. Avoid extended discussion about requests. We don't have to agree about a close/delete request. We're not a democracy. However, users posting requests that are blatantly wrong will be told so. The final verdict is on the RO team.](https://socvr.org/faq#GEfM-avoid-extended-individual-cv-pls-discussion)"

Obviously, that FAQ entry is not as structured as what's proposed here.

**Comment by makyen** [comment]
Are you saying that requests should be binned when there is disagreement with the specific stated close reason, even when the question may be closable for other valid reasons? In other words, are you suggesting that we bin requests in order to change the reason for the request? Or, should this only be a process that's used when there is agreement among 3 people, including 1 RO, that the question should remain open?

**Comment by Tyler-H** [comment]
@makyen I would prefer even when the question may be closable for other valid reasons, though I would certainly rather accept 'only when the question should remain open' than the status quo remain as it is. 

The reasoning is that it's trivial for the requestor (or any additional party) to make a second/modified request in the event that the question is close-worthy for another/more proper reason if the original request is binned. It's also trivial, in the event of an improper binning, for any RO to *un*-bin said request, as all active ROs are also ROs in each of the request archival rooms.

It's *less* trivial for objecting users to track the question for an indeterminate amount of time in the event a reopen-pls request needs to be posted (and no one has offered an argument that it's actually cv-worthy for some other reason, as you did re: this case and the MCVE reason), and then, *on top of* tracking the question's status over potentially multiple weeks, garner enough reopen votes to get the question reopened.

Further, what we should strive to keep in mind is that we operate at the pleasure of Shog as a coordinated voting mob (albeit highly restricted). In other words, the onus is on us as a room to be as above board and exemplary as possible, and this scenario should not be any different. As our FAQ page states, we should avoid even the suggestion or hint of impropriety or other inappropriate mob/voting-based behavior because of the sensitive nature of our existence. The standards of SOCVR are different (read: higher) than those applied to questions organically (specifically, the community consensus, I think, is to not reopen close-worthy questions just to re-close them with a "better" reason) - the process here will serve multiple purposes:

- it will offer an avenue for preventing/guarding against abuse by otherwise-serial abusers *before* they become 'abusive' or 'bad faith' requestors.
- it will offer an opportunity for education in the likely event that a user was simply mistaken or didn't know enough about the topic.
- it will prevent questions from being wrongly closed (even if that means a close-worthy question being closed for an inaccurate reason) by those users/members who might flirt a bit with robo-reviewing (either out of habit or because it's been a long day or there's been a lack of sleep; we all have moments where we goof up or maybe trust requestors' judgment a bit too much).
- it will prevent Meta from using as an arguing point "they regularly close questions for any reason under the sun, whether the reason even applies or not! See all these examples..."

And, for what it's worth, I think this clashes a bit with rule 14, which I don't personally agree with (at least not hard-and-fast; I think there ought to be *some* avenue for extended discussion about requests, if for no other reason than they can morph into general rules/behavior discussions like the one today, which I felt was both polite and productive).

<strike>Also I have noticed I did not mention anything about the requestor responding - I will try to edit the topic suggestion to include some verbiage on that some time before our next room meeting (and hopefully sooner rather than later) - I do think the requestor should have an explicit opportunity to defend their argument; e.g. if they can provide a reasonable/logical argument for why they posted it that way, and thus the disagreement is ultimately a matter of differing **informed** opinions, then the request would not be 'actionable'.</strike> 

**Edit** - I've now added a bit about the requestor defending their reasoning.

**Comment by makyen** [comment]
Just FYI: This was previously discussed in a Room Meeting as # 3 In January 2017: ([summary](https://socvr.org/room-info/room-meetings/2017-01)) ([discussion](http://chat.stackoverflow.com/rooms/108179/conversation/2017-january-topic-3))

**Comment by AdrianHHH** [comment]
I think I have been guilty of using the wrong close reason in a cv-pls and then wondering what to do. It might be helpful for the FAQ to discuss the topic. I am not sure whether a CV can be retracted and another CV for a different reason be issued. Is changing the CV necessary if a cv-pls is deleted and a cv-pls with a different reason issued? I don't mind if one of my cv-pls requests is deleted by a RO, although it would be nice to be told with a reason.

**Comment by makyen** [comment]
@AdrianHHH Unfortunately, once you retract a close-vote, you are not able to vote to close the question again. Thus, there's no way to change the reason which you used. You either have to accept that your CV is for a reason you consider wrong, or retract it. I've chosen both options from time to time, depending on if my CV will result in the displayed reason the question is closed being wrong, traded-off with how urgent it is that the question be closed (i.e. if I retract, that means that yet another person has to VtC).

If you choose, having the wrong close reason can be mitigated by leaving a comment on the question stating the real reason that the question should be closed. I've also done this on occasions where the question should be closed, but there are already at least 3 votes for a wrong reason prior to me placing a CV.
