### ISSUE TITLE
Off-topic chatter should not be allowed, only messages with *-pls requests are welcome

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/room-meeting-topics#25]
SOCVR should only accept close (reopen, etc etc) requests and all the other chatty messages should be avoided 

source: https://meta.stackoverflow.com/questions/380448/off-topic-chats-in-so-chat-rooms
from: https://meta.stackoverflow.com/users/9134576/zlytherin

**Comment by Tyler-H** [comment]
Is this serious?

**Comment by Cerbrus** [comment]
It is.

I strongly disagree. I think the current ruling is quite strict already. 
I'd be more lenient than the current standard, if it were up to me.

**Comment by machavity** [comment]
@Tyler-H We're taking it seriously, as it was posted as such on Meta. We can discuss in the next meeting.

And, yes, I disagree with it.

**Comment by makyen** [comment]
The up/down indications on this topic are quite clear. It doesn't appear that we need to actually discuss this. In closing this, I'm not intending to prevent further adjustment to accommodate what people want in the room. However, if we are to have it as a topic for a room meeting discussion, then it should be reformulated and be more focused in a direction that has a reasonable amount of support.
