### ISSUE TITLE
How should we deal with requests related to Meta discussions?

### ISSUE THREAD

**Issue by machavity** [SO-Close-Vote-Reviewers/room-meeting-topics#28]
We had an issue with a pair of questions being discussed on Meta. Question 1 had been marked as a duplicate of Question 2, which had resulted in [this Meta.SO question](https://meta.stackoverflow.com/questions/381595/mark-as-duplicate-after-2-5-years). Meta effect had reopened Question 1. That prompted two separate users (one of whom had closed Question 1) to post cv-pls requests. The request on Question 2 was binned for being on an inactive question (12 months). The request on Question 1 was binned for being on an active Meta discussion (Meta had just reopened it). The person who opened the CV on Question 1 had been the hammer that closed it previously.

There are no official rules on this, but perhaps we need to amend [Rule 11](https://socvr.org/faq#GEfM-cv-pls-not-a-habit) as such

1. Questions under *active Meta discussion about what to do* should be off-limits. For our purposes here, an active Meta discussion is where the course of action is unclear and changing.
2. Any request (*-pls) prompted by a recently active Meta discussion should disclose that. Voters are held accountable for their votes and not disclosing that opens voters to potential liability on Meta

We also probably need to amend [Rule 15](https://socvr.org/faq#GEfM-no-requests-youre-involved)

- If you previously took visible action(s) on a question or answer (i.e. closed, re-opened, etc), and those action(s) are called into question on Meta, then you are considered "involved" with that question

**Comment by gunr2171** [comment]
Side note, we might want to think about a different numbering strategy for the rules. Adding a new one throws off all the existing rule numbers.
