### ISSUE TITLE
When should queues be allowed to avoid the "recent" rule?

### ISSUE THREAD

**Issue by machavity** [SO-Close-Vote-Reviewers/room-meeting-topics#29]
A question was presented today from the site Close Queue that was well outside the active window. When the user was reminded that a question needed recent activity in accordance with Rule #11, they asked why a Suggested Edit could be OK but not a CVQ entry. It's not clear we've ever set any official rules to this effect. The proposal here is to formalize the following:

A question is considered `active` by SO when it is

- Edited (either by 2k+ edit or through an approved edit)
- Answered (i.e. NATO)

Comments and review queues by themselves do not change this. Logically, it would be acceptable to throw a Suggested Edit (not made by the requester, per Rule #27) into that mix as well (since someone is trying to edit the question, and thus make it active). The theory here is that we don't want to necessarily see someone approve an otherwise meaningless edit, just to make the question active, and thus CV-able. 

Conversely, it would not make sense to allow this exception for other review queues. By definition, Triage, H&I, First Posts and Late Answers(NATO) deal with questions that are already considered active. Most of LQP is on newer answers (i.e. the question would be active anyways), so a CV from there that wouldn't normally qualify should be rare. Reopen Queue doesn't need CVs because it's already closed. 

That leaves the Close Queue, and we've made it clear we don't want CV-ing to become a habit. If a user comes across a question in the Close Queue, that should not, in of itself, allow a CV to be posted. It's already in the queue, and it could have been started by the requester (you can't tell until the review is completed). As such, it doesn't make sense to extend this exception to an active CVQ review. 

There could be one edge case that would, however, be acceptable. If a user comes across a CVQ  that they did not start, that closure is rejected, and the user feels strongly that the question should be closed, they can post a CV on it. This requires the user to watch the review for its rejection, which is not an easy process. Like [del-pls], the nuisance factor of watching a specific review should be enough of a deterrent that these should be rare.

The proposed syntax here would be

`[tag:cv-pls] Close Reason Here /some/question/link (related to /some/review/link)`

**Comment by Tyler-H** [comment]
What about edits to answers? That bumps the question to the front page, but is not an edit to the question. Answer edits also update the "last active" link at the top-right of the question page.

**Comment by machavity** [comment]
Small omission on my part. Everything I said would apply to answer edits as well. The principle is we don't want to encourage minor (normally disapproved) edits being approved just to make the question a valid CV target.

**Comment by makyen** [comment]
If we do this, I'd suggest using a slightly different format:

    [tag:cv-pls] Close Reason Here (related to /some/review/link) /some/question/link

In all other cases, the question link comes after the free-form portion of the request. IMO, it would be better to have the format more closely match what is used elsewhere.

I also find it convenient to be able to know that in most cases the last question/answer link is the one that the request is about. This is obviously not the case for some manually created requests, but it is for all those created by the Request Generator. The only link after the one linking to the focus of the request is the one to the user.
