### ISSUE TITLE
Remove link to user in cv-pls request

### ISSUE THREAD

**Issue by jdd-software** [SO-Close-Vote-Reviewers/room-meeting-topics#3]
Should we remove the link, keeping only the user name (to track stalkers) from the cv-pls user-script?

As I see it, it is of no use (you only risk mis-clicking) and probably it is also politically incorrect. (don't link user profile's in chat).

**Comment by gunr2171** [comment]
Co-proposal: remove the time stamp for when the question was asked. I find that useless.

**Comment by Bhargav-Rao** [comment]
@gunr2171 I'm against removing the timestamp. it clearly indicates whether a post is new or old. Posting CV-PLS on old posts is restricted. The timestamp helps to enforce that restriction.

**Comment by Tiny-Giant** [comment]
I'm against removing at least the user _name_. We do not allow cv-pls requests for multiple posts from the same user. Having the user name there is an easy way to identify when people are doing that. The link to the profile is probably unnecessary.

**Comment by NathanOliver1** [comment]
@Bhargav-Rao cv-pls on old questions are discouraged because there is newer stuff we can focus on but they are not, not allowed.

**Comment by Bhargav-Rao** [comment]
Hah @NathanOliver1, that's why I used the word "restricted" 😉

**Comment by Aralun** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-may-topic-4)

While no ones sees any issue in itself in removing the link, there has been concern expressed on how some policies (mainly the no-harassment one) can be difficult to follow, even by well-meaning regulars. This should further be discussed and clarified.
