### ISSUE TITLE
"has no value to stay on site" is not a valid delete reasons

### ISSUE THREAD

**Issue by Aralun** [SO-Close-Vote-Reviewers/room-meeting-topics#35]
Content should be deleted when it offers absolutely zero value to the site. However, _why_ it lacks any value should be explained, for example ("nth duplicate"). As such the "has no value to stay on site" del-pls example should be deleted from the FAQ.

**Comment by kamil-tekiela** [comment]
I would propose to standardise the reasons why we are requesting the deletion. It would avoid ambiguity. nth duplicate is a common cause for confusion. Unneeded duplicate is also quite ambiguous. A list of clearly defined reasons could help us to determine quicker why the SME thinks it is not needed. It should also cover the emergency deletions (20k).

**Comment by makyen** [comment]
The text "has no value to stay on site" dates from sometime prior to the content of the FAQ being [moved to it's current repository](https://github.com/SO-Close-Vote-Reviewers/socvr-website-content/blob/1138f44db816505e121cee90f32e4b8f3492e26c/pages/faq.md) on 2017-03-17. Coming up with/picking an example which exemplifies what's desired and also fits into a small number of words is something that does require some thought when composing such examples. I don't know why that specific text was used, but I suspect that it was just what the person who wrote it came up with in the moment.  I don't recall anyone expressing attachment to that particular text.

If we want to use different example text, I'm not seeing changing it as something we need to discuss in a room meeting, unless there's objection to the new wording which can't be resolved, or that people feel using different wording is a change in policy.

As far as I'm aware, the intent behind request reasons has always been that the requestor would explain, at least minimally, why the request was being made. For `del-pls` that would be why the post should be deleted, which implies saying more of the *why* behind the post "has no value to stay on site".

**Comment by rschrieken** [comment]
I would add that we have a larger pending topic to re-organize the FAQ and while we all agree this needs to be done, no-one is taking up that challenge. Given events over the last 6 to 8 months I can understand why motivation dropped a bit. I prefer the rewording of things is done/reconsidered as part of that bigger effort.

**Comment by codygray** [comment]
I dislike the idea of standardizing the reasons for `del-pls`. If you're making a request for deletion, you need to be prepared to articulate clearly and in detail why the post should be deleted. You are requesting an *exceptional* action, so exceptional detail is required. (If the deletion reason is non-exceptional, there will be a standard flag reason for it.)

I am not much in favor of the particular phrasing "has no value to stay on site". I would prefer that we change that example wording. It needs to give a *reason* why the post has no value to stay on the site. I don't particularly care for "*n*th duplicate", either, as that ignores the fact that there can be value in having *n* rewordings of the question to serve as signposts.

**Comment by makyen** [comment]
The examples given in the FAQ were only ever intended as examples of the *format* which is used for requests. They were not intended as the exact text which one should use for a request reason.

I've updated that section to show:

>Other `-pls` requests follow the same format (again: keep it on one single line, do not add linebreaks!):
>
>     [tag:reopen-pls] post now has enough info https://stackoverflow.com/q/12345
>     [tag:del-pls] <explain why it should be deleted now> https://stackoverflow.com/q/12345
>     [tag:delv-pls] <alternate request name to del-pls; other than that, use the del-pls format>
>     [tag:undel-pls] <explain why should it be undeleted> https://stackoverflow.com/q/12345
>     [tag:review-pls] Removes plagiarism, has reject vote https://stackoverflow.com/review/suggested-edits/12345
>     [tag:spam] https://stackoverflow.com/q/12345
>     [tag:offensive] https://stackoverflow.com/q/12345
>     [tag:flag-pls] <state the flag type and why> https://stackoverflow.com/q/12345
>     [tag:reflag-pls] <state the flag type and why> https://stackoverflow.com/q/12345
>The above are intended as examples of the format used for the various requests. The text used for request reasons in the examples are just placeholders, which are here just for the examples and shouldn't be the exact text you use. Your request reasons should be specific to the reasons you're making the request you are posting. There are some guidelines in the next section for what should be in a request reason.

In addition, I'd point our that the next section, which is "[What Should Request Reasons Contain?](https://socvr.org/faq#what-should-request-reasons-contain)", in addition to general requirements for request reasons says the following about request reasons for `del-pls` requests:

> * For `del-pls` requests: Indicate why the post should be deleted and not just remain closed or wait until the Roomba gets it; deletion is an exceptional act and should be treated as such. If the post can only be delete-voted by users with >20k reputation (e.g. any answer), then it's helpful to indicate that with a `20k+` tag. It's also helpful to briefly indicate if the Roomba will, or will not, delete the question. The fact that the Roomba won't delete a question is a contributing factor to needing delete-votes. [Generally, unless it's urgent to delete a question, it's normal to allow the Roomba to delete the question rather than post a `del-pls` for it, if the Roomba will delete it in the relatively near future.]

**Comment by makyen** [comment]
From my point of view, the original request here has been resolved by the change to the FAQ. If there is a residual issue which still needs to be discussed at a room meeting, then it seems to me that it would be best to create a new Issue topic which is focused on whatever that issue is.
