### ISSUE TITLE
Can the cv-pls request reasons be abbreviated and if yes, what should they be?

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/room-meeting-topics#37]
In the userscript the "c" will output "Needs Details or Clarity" but if you can't use the userscript that is a lot to type.

For those cases being able to shorten it to NDC would save time / effort.

What abbreviations can we use in the transcript?

**Comment by makyen** [comment]
"Unclear", which was the old name for that close reason, seems to still fit with "needs ... clarity" and is both significantly shorter and still intuitively understandable. If you're creating requests by hand, I'd suggest using that as an abbreviation.

**Comment by makyen** [comment]
Without concrete suggestions as to what the abbreviations should be, which the room meeting could then be chose between, I don't think this is a productive topic for a room meeting. Room meetings have very little time allocated for each topic, which doesn't really allow for having a brainstorming session for several different things.

I'm not adverse to people making suggestions for what abbreviations we can/should use. I just don't think this is an appropriate room meeting topic in its current form.
