### ISSUE TITLE
When are too many cv-pls, too many?

### ISSUE THREAD

**Issue by jdd-software** [SO-Close-Vote-Reviewers/room-meeting-topics#4]
This topic is not intended to create a rule, but to give reference for new user on how the members of SOCVR evaluate the number of cv-pls request sent by a single user, lets create some guidelines.

**Comment by gunr2171** [comment]
Here is some preliminary information. I hope I did the calculations correctly.

> What is the average number of cv-pls's that a person posts in any SOCVR room in a given month?

![image](https://cloud.githubusercontent.com/assets/8290105/26263094/42363424-3ca5-11e7-958b-49923e147db0.png)

Looking at one month, about 25% of users contribute 80% of the cv-pls requests.

![image](https://cloud.githubusercontent.com/assets/8290105/26263461/e4b0ff4e-3ca6-11e7-9757-6575a8baf910.png)

Here is the most cv-pls's a person has posted on a single day (ignoring anyone who has had less than 3 as a max-per-day)

![image](https://cloud.githubusercontent.com/assets/8290105/26265675/121ef64e-3cb0-11e7-98ba-0d7e2f5d5f7a.png)

And here is that data in buckets, to show that 60% of users post a max of 4 or less cv-pls's in a day, 30% between 4 and 13.

![image](https://cloud.githubusercontent.com/assets/8290105/26265716/38767a4c-3cb0-11e7-8712-7b54f257ae49.png)


Still working on getting more useful data, and I'll update this message if my math was wrong.

**Comment by Aralun** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-may-topic-2)

Keep the current guidelines of not posting walls of requests (max 4 or 5 in a row), remind regulars to review SOCVR requests.
