### ISSUE TITLE
Queen is breaking all our trains... How much can we take?

### ISSUE THREAD

**Issue by double-fault** [SO-Close-Vote-Reviewers/room-meeting-topics#6]
Uh, [this topic by petter](https://github.com/SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io/issues/11) missed two meetings, making a new issue here so that it can be raised in this meeting.

> Queen is passing duplicate notifications, she has started to send offensive comments... How much can we take of this breaking train bee?
> Let me give you some stats about all the dupes closed and tell me what you think.

**Comment by Aralun** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-may-topic-5)

We should ask bot authors to make sure their code doesn't flood the room with messages and requests, possibly implementing batching or self-deletion. For now, regulars and ROs don't find the bots too noisy as they rarely ever break a conversation.
