### ISSUE TITLE
Should people be allowed to use the cv-pls requester script if they are not present in the room?

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/room-meeting-topics#7]
As an RO, I've noticed instances where people drop many close vote requests into the room when they are not in the room themselves. While most of the time the requests are valid, if people have feedback to give it there is no good way to notify the poster. It takes (by default) 15 minutes for a ping in chat to reach a person's inbox.

**Comment by rschrieken** [comment]
Allowed? Is there a way we can notice? Posting while not in room is a feature ...

**Comment by tripleee** [comment]
Perhaps there should be guidance to _suggest_ you visit the room if you send [tag:cv-pls] requests to it, without making it an out-and-out requirement? The cv-pls userscript is convenient precisely because you don't have to be in the room at that very moment, although I agree it would be good hygiene to make sure you are available for follow-up. How about, **make sure you are pingable?**

**Comment by makyen** [comment]
Just the fact of posting the `cv-pls` would make you pingable in the room. I'm not sure if that would last beyond the `cv-pls` being moved to the Graveyard, if that was the user's only post in the room. However, unless the user had some tab open to chat.SO, then the ping won't show up until the delay the user has configured has expired and it shows up in their SE inbox (if they are still on SO/SE).

Are we saying we want people to remain physically available to get pings (immediately) for X minutes after posting (i.e. have any chat.SO tab open)?

**Comment by Tyler-H** [comment]
How would we enforce this? How do we know someone is actively the room with the tab open and focused, vs looking at another tab, vs not having the room open at all but having recently posted via the script or organically and then closing the tab but still being pingable? In the same vein as Makyen's comment, what exactly does "present" mean?

**Comment by tripleee** [comment]
Then how about a rule to suggest that if you don't respond to pings within (say) 30 minutes, your `cv-pls` is eligible for removal to the graveyard or somewhere else outside the room? That would shift the attention back to something actually actionable and enforceable, and send the signal to dissuade users from dumping stuff and then leaving.

**Comment by gunr2171** [comment]
(no offence to tripleee), this is such an old post and I agree with the stated pushback and concerns. If this needs to be brought up again we'll do so as a new post with more modern context.
