### ISSUE TITLE
Are proofread requests allowed?

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/room-meeting-topics#8]
In the rare occasions  that I post an answer I would really love to have it proofread by a native speaker. It seems a bit cumbersome to head off to English Learner chat or Writers.se. 

Instead I would like to ask the regulars of SOCVR to proofread my post to iron out the most obvious spelling and grammar mistakes. 

However, the room has already several rules that prohibit to link to your own post, or posts you have a stake in. Can I request the room to scrutinize my own post for quality or is this a conflict of interest?

If I can, what would be the preferred format and/or etiquette?

_I hope I made many mistakes in this topic_

**Comment by NathanOliver1** [comment]
I feel that as long as we are clear this is a request to edit/give pointers and not a look at this and vote on it then we are fine.  Improving the quality of the site is something we should want to partake in.

**Comment by mogsdad** [comment]
A review of a file before it's on an SO site would avoid the possibility of
garnering votes, so that might be a good compromise.

**Comment by jdd-software** [comment]
It's probably better to keep these request out of SOCVR chat transcript. 

I think either Mogsdad solution should be used or the user can ask in room if someone is up for the proof reading, if so start a private chat and pass question/answer in that room where the discussion related to the question/answer can be kept.

**Comment by Aralun** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-may-topic-3)

> Those requests are tolerated, however it would be better to host such activities outisde of SOCVR (GitHub Gist or another chatroom).
