### ISSUE TITLE
Can we add the rule against gold-badgers not asking for tag edits to the "rules" page?

### ISSUE THREAD

**Issue by Tyler-H** [SO-Close-Vote-Reviewers/room-meeting-topics#9]
During one room meeting we decided that:

"It seems we have reached a consensus: we will not allow tag-editing for handing off to gold badge holders."

https://chat.stackoverflow.com/transcript/message/29750947#29750947

However, this decision is only reflected in the team meeting minutes on socvr.org, and is not listed anywhere in the 'general expectations' or rules for members. Seeing as how this is an expectation for members, can it please be added to the list of rules somewhere?

**Comment by rschrieken** [comment]
https://github.com/SO-Close-Vote-Reviewers/socvr-website-content/commit/8b0ed47f5aeff0f38dbad7f0487454c5b75bb55a
